### PR TITLE
added js-semantic to js-templates.cson

### PR DESCRIPTION
**Pull request by bruinebeer**
Hi, added snippets support for js-semantic grammar. Cant live without it ^^. Please Accept. Cheers!

### CODE REVIEW

**Comment by bruinebeer** [comment]
Hi, added snippets support for js-semantic grammar. Cant live without it ^^. Please Accept. Cheers!

**Comment by outsideris** [comment]
@bruinebeer What is js-semantic for?

**Comment by bruinebeer** [comment]
Its an alternative grammar for javascript in atom. It colors every var differently so you can identify them easier (also makes typos less likely).

Snippets for Js dont work since its an whole other grammar, what i added provides support for the language.

[Atom Js Sematic](https://atom.io/packages/language-javascript-semantic)

**Comment by outsideris** [comment]
I got it. Thank you.

**Pull request merged**
